### ISSUE TITLE
Github Login -> Duplicate entry '' for key 'email'

### ISSUE THREAD

**Issue by nickurt** [zendframework/modules.zendframework.com#188]
When using the github login ...

    SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '' for key 'email'

**Comment by localheinz** [comment]
@nickurt @cerealean @ZeinEddin @codeliner @snapshotpl 

Can any of you confirm that this is still an issue?

**Comment by ZeinEddin** [comment]
I just tried to login and it worked fine... (y)

**Comment by localheinz** [comment]
@ZeinEddin 

Closing this, then. Thank you!

**Comment by snapshotpl** [comment]
It's working! :+1:

**Comment by gianarb** [comment]
![giphy 1](https://cloud.githubusercontent.com/assets/1630267/6347260/b670a354-bc16-11e4-8afa-731110540f2d.gif)

Other gif!!

**Comment by nickurt** [comment]
Works :+1:

**Comment by codeliner** [comment]
works for me, too. Many thanks.
