### ISSUE TITLE
Github information not found

### ISSUE THREAD

**Issue by cerealean** [zendframework/modules.zendframework.com#189]
When I am trying to add modules or go through my organizations, none of my information is being found. I originally thought this was related to [this issue](https://github.com/zendframework/modules.zendframework.com/issues/188), however my coworker [lepermessiah57](https://github.com/lepermessiah57) did not have login issues and his Github information is not being loaded either.

When I click "My Modules", it says *No Modules Found*. When I click "My Organizations", it does not even give me a message. The same happens for my coworker. Any help or advice is appreciated - thanks!

**Comment by localheinz** [comment]
@cerealean 

Closing, as adding module works, at least for me. Please re-open when you encounter the problem again!
