### ISSUE TITLE
Proxy Error

### ISSUE THREAD

**Issue by stevleibelt** [zendframework/modules.zendframework.com#197]
I've no idea why but whenever I want to go to "My Modules" section it get the following error as response (in the hidden [AJAX](http://modules.zendframework.com/module) call).

```
Proxy Error

The proxy server received an invalid response from an upstream server.
The proxy server could not handle the request GET /module.

Reason: Error reading from remote server

Apache Server at modules.zendframework.com Port 80
```

I've no idea how to debug this but I would like to add my module to the index.

**Comment by gianarb** [comment]
Reference #353

**Comment by localheinz** [comment]
Unable to reproduce at the moment, closing.

@stevleibelt 

If you still see this issue, please re-open!

**Comment by stevleibelt** [comment]
@localheinz 

Still the same, did a check on chromium v40.x

Console Log:
```
 GET http://zfmodules.com/module 500 (Internal Server Error)jquery-1.11.2.min.js:4 m.ajaxTransport.sendjquery-1.11.2.min.js:4 m.extend.ajaxjquery-1.11.2.min.js:4 m.fn.loaduser:176 (anonymous function)
```

When I reload the page itself (meaning the chosen tab is switched back to "Registered Modules", I could find the following error in the Network Log:
```
Warning: array_filter(): An error occurred while invoking the filter callback in /var/www/modules/module/ZfModule/src/ZfModule/Controller/IndexController.php on line 148

**Comment by gianarb** [comment]
@stevleibelt thanks! But maybe this is another issue, it is not a proxy error now :weary:

**Comment by stevleibelt** [comment]
@gianarb you are true. It is always hard to decide if reopen an existing (but technically not fitting) defect or create a new one and refer to the the existing one.

Thanks for the work so far :+1:

**Comment by gianarb** [comment]
Thanks for this bug reporting! :+1:

**Comment by ins0** [comment]
maybe this is a fatal error when the rate limit is reached for github?

**Comment by gianarb** [comment]
Yes for me this is the problem.. :+1: @stevleibelt sorry what's your repositories number? Thanks

**Comment by stevleibelt** [comment]
@gianarb I only have around 52 repositories :-/

**Comment by gianarb** [comment]
maybe the limit is 30

**Comment by snapshotpl** [comment]
I have 43 repos and "My modules" page is working.

**Comment by gianarb** [comment]
Perfect thanks! The number of repo is not the problem..

Gianluca Arbezzano
Il 24/feb/2015 18:42 "Witold Wasiczko" <notifications@github.com> ha
scritto:
