### ISSUE TITLE
Cannot add new modules any more

### ISSUE THREAD

**Issue by prolic** [zendframework/modules.zendframework.com#201]
I go to http://modules.zendframework.com/user and click on "My Modules". It comes a preloader-image with the message: "Synchronizing with Github". That's it. Never got any further. It used to work in the past, but the last modules I published couldn't get annouced at modules.zendframework.com.

**Comment by heiglandreas** [comment]
Still same here. A call to http://zfmodules.com/module results in the following reponse: 

Warning: array_filter(): An error occurred while invoking the filter callback in **/var/www/modules/module/ZfModule/src/ZfModule/Controller/IndexController.php** on line 148

**Comment by gianarb** [comment]
Maybe the problem is number of repositories [Reference #353], @prolic I see your last module updated :)
Now it works?

@heiglandreas this is another but, I have it.. thanks

**Comment by prolic** [comment]
Yes, just received the post from the mailing list and retried to resubmit
some of my modules. And it worked this time again!
Thanks to whoever fixed it! ;-)

Prolic

Sascha-Oliver Prolic

2015-02-24 9:06 GMT+01:00 Gianluca Arbezzano <notifications@github.com>:

**Comment by gianarb** [comment]
Thanks for your tests @prolic!

@localheinz  you can close it

**Comment by localheinz** [comment]
Thank you, @gianarb and @prolic!
