### ISSUE TITLE
unregistered repositorys can be viewed on detail page

### ISSUE THREAD

**Issue by ins0** [zendframework/modules.zendframework.com#246]
if a user create on github a repository name that is allready registered on site - the detail view checks if the repo name is registered found a registered module like ``someuser/test-repo`` and allow the view to ``ins0/test-repo``

i create a test issue repo - http://modules.zendframework.com/ins0/ZF2-AcYaml

**Comment by localheinz** [comment]
@ins0 

Looking at this I'm thinking that generally the site would benefit from identifying modules by vendor **and** name, what do you think? 

Who cares if there is more than one module with the same name, if one of them is better than the other, or just serves a different purpose in the first place? 

See, for example, https://packagist.org/search/?q=theme

![screen shot 2015-02-17 at 19 59 13](https://cloud.githubusercontent.com/assets/605483/6235023/8ad1464a-b6df-11e4-8f52-36653073a3fe.png)

The same restrictions that we currently have could still apply, specifically

* repository can not be a fork 
* submitter needs to have push permissions

Thoughts?

**Comment by localheinz** [comment]
@ins0 

Just gave this a spin and also created a repository: https://github.com/localheinz/ZF2-AcYaml.

Here's what I got when navigating to http://modules.zendframework.dev/user:

![screen shot 2015-02-17 at 22 52 27](https://cloud.githubusercontent.com/assets/605483/6238005/d58337b2-b6f7-11e4-81ee-2b172b4e74c7.png)
