### ISSUE TITLE
Urgent: Rename domain name to zf2modules.com

### ISSUE THREAD

**Issue by GeeH** [zendframework/modules.zendframework.com#284]
At the moment, the domain name modules.zendframework.com is under the control of Zend. As they don't want to point their domain name at an external server, at this point there is a proxy server at Zend that forwards all requests to modules.zendframework.com to the internal domain name of the server at Roave.

It seems that this server is currently down, and getting some answers and support from Zend as to where it is and who can fix it is very difficult.

Today, the domain name zf2modules.com (which has also pointed at the modules website since it's inception) became available to buy, so I bought it. It is now under the control of Roave. I propose, at this point, that we rename the website to zf2modules.com so that we have control over the domain name. 

To provide backwards compatibility I will then get Zend to http forward  modules.zendframework.com to zf2modules.com. 

The added benefit here is that I will buy the https certificate for zf2modules.com so in the future we can flip the site to be https only.

Thoughts?

**Comment by localheinz** [comment]
@GeeH 

> The new server is now serving the site, it's running Nginx and PHP FPM 6.5.4. Currently is it designed to respond to only zfmodules.com with modules.zendframework.com and zf2modules.com doing a http redirect to zfmodules.com.

Is that actually **PHP 5.6.4**? Asking for a friend!

/cc @ins0

**Comment by qmanjr5** [comment]
Yes, it is using PHP 5.6.4.

**Comment by localheinz** [comment]
@qmanjr5 

Thank you, that is really great to hear!

@ins0 

You can disregard my comments related to this, then!

**Comment by localheinz** [comment]
@GeeH 

Any news on this one?

**Comment by GeeH** [comment]
No


On 12 February 2015 at 13:39:36, Andreas Möller (notifications@github.com) wrote:

@GeeH

Any news on this one?

**Comment by localheinz** [comment]
![carol-beer-1024](https://cloud.githubusercontent.com/assets/605483/6169013/68df2890-b298-11e4-843e-9eda26e8db48.jpg)

**Comment by localheinz** [comment]
Related: application is currently available at both

* http://modules.zendframework.com
* http://zfmodules.com

**Comment by gianarb** [comment]
maybe this issue is closable

**Comment by localheinz** [comment]
I think it is, zfmodules.com works fine for now, doesn't it?

We've got redirects in place from

* http://modules.framework.com
* https://modules.framework.com
* http://www.zfmodules.com

and this domain is good to serve modules for ZF2.
