### ISSUE TITLE
Github API calls not authenticated?

### ISSUE THREAD

**Issue by ins0** [zendframework/modules.zendframework.com#288]
I just notice that the current example configs don't configure the EdpGithub service with a valid client id and client secret (only SocialAuth).

can someone with full access to the server please check if EdpGithub gets configured in one of the application configuration files?

just to make sure our api calls against github are not more limited because of unauthenticated requests.

**Comment by ins0** [comment]
ping @GeeH

**Comment by ins0** [comment]
@geeh got some time to setup a config file for the github client? as we now the request are not authenticated against the api?

**Comment by GeeH** [comment]
I have a prototype solution that works, will pr today

**Comment by ins0** [comment]
sounds good thanks
