### ISSUE TITLE
Login from zfmodules.com via github doesn't seem to work

### ISSUE THREAD

**Issue by heiglandreas** [zendframework/modules.zendframework.com#296]
Sorry to say, but *I* encounter an error-message when I try to log in via github.

To reproduce:

Open http://zfmodules.com and click onto the "Github login" link.

I then see the URL http://www.zfmodules.com/user/login/github being called and the server returns 

    This view is generated by the Error Module
     An error occurred
    An error occurred during execution; please try again later.

Or is that just me having misconfigured my machine?

**Comment by gianarb** [comment]
I don't know but maybe.. today there is a different problem 
If you click to Login return this:

http://modules.zendframework.com/?error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdeveloper.github.com%2Fv3%2Foauth%2F%23redirect-uri-mismatch

**Comment by GeeH** [comment]
it's weird, the github application actually has the right callback url. I'm stumped.

**Comment by ins0** [comment]
@GeeH is the redirect url with url path or just the host? so it should be only ``http://modules.zendframework.com/`` as callback

**Comment by GeeH** [comment]
Which is exactly what it is!


On 24 January 2015 at 19:49:29, Marco Rieger (notifications@github.com) wrote:

@GeeH is the redirect url with url path or just the host? so it should be only http://modules.zendframework.com/ as callback

**Comment by ins0** [comment]
go home github api you're drunk :beers:

**Comment by ins0** [comment]
@GeeH don't know where but the redirect to github looks on production like this ``https://github.com/login/oauth/authorize?client_id=e00c0cc9c5eab5a04653&redirect_uri=http%3A%2F%2Fzfmodules.com%2Fscn-social-auth%2Fhauth%3Fhauth.done%3DGitHub&response_type=code&scope=user%2C+public_repo%2C+`` so the github application configured is not from the github account where u lookup the url or somewhere in the project folder overrides the redirect url.

**Comment by GeeH** [comment]
OK, I need to figure out where that url is configured, and how to fix it; thanks!


On 25 January 2015 at 03:01:26, Marco Rieger (notifications@github.com) wrote:

@GeeH don't know where but the redirect to github looks on production like this https://github.com/login/oauth/authorize?client_id=e00c0cc9c5eab5a04653&redirect_uri=http%3A%2F%2Fzfmodules.com%2Fscn-social-auth%2Fhauth%3Fhauth.done%3DGitHub&response_type=code&scope=user%2C+public_repo%2C+ so the github application configured is not from the github account where u lookup the url or somewhere in the project folder overrides the redirect url.

**Comment by gianarb** [comment]
Hi @GeeH! Have you news for this problem?
Thanks!

**Comment by localheinz** [comment]
@heiglandreas 

I understand this issue as this

### Scenario 1

* navigate to http://zfmodules.com
* sign in with GitHub
* get redirected to http://modules.zendframework.com with a `redirect_uri_mismatch` error

But we also have 

### Scenario 2

* navigate to http://modules.zendframework.com
* sign in with GitHub
* get redirected to http://modules.zendframework.com with a `redirect_uri_mismatch` error

Not sure what's the actual deal with this. 

What I can tell from **Scenario 1** (redirects to http://modules.zendframework.com) and also from https://github.com/zendframework/modules.zendframework.com/issues/296#issuecomment-71328791, at least **Scenario 2** should work.

**Comment by ins0** [comment]
just pointing out https://github.com/zendframework/modules.zendframework.com/issues/296#issuecomment-71346840

notice -> http%3A%2F%2F**zfmodules.com**%2Fscn-social- [...]

**Comment by localheinz** [comment]
@ins0 

Good catch, updating my comment above!

**Comment by localheinz** [comment]
@Ocramius @GeeH 

Can you have a look? I know the two of you are really busy, but we **need** to get this sorted out!

**Comment by GeeH** [comment]
If you can tell me what I need to do in simple terms I will do it asap :cactus:

**Comment by ins0** [comment]
@GeeH  Hard to say. Can u confirm that the used Github Token in the Config files is equal to the Github Application where you edit the Callback Url? Maybe Cache?

**Comment by GeeH** [comment]
@localheinz can I get you access to the server; would that work better?

**Comment by ins0** [comment]
@GeeH just talked about this on IRC with @localheinz that would make things alot easier if andreas agrees :+1:

**Comment by GeeH** [comment]
@localheinz I'll get this sorted with Kairos if you're ok with it

**Comment by localheinz** [comment]
@GeeH

:+1:

**Comment by localheinz** [comment]
@GeeH 

Got access now!

However, what is apparent from https://github.com/zendframework/modules.zendframework.com/issues/296#issuecomment-75048763:

![screen shot 2015-02-20 at 13 09 17](https://cloud.githubusercontent.com/assets/605483/6285909/c654eaae-b901-11e4-854c-012c13af2cef.png)

Sorry to bug you with this, but can you please have a look at the [GitHub Application setting](https://github.com/settings/applications) again?

**Comment by GeeH** [comment]
yes, I’ll bug @akrabat after his talk


On 20 February 2015 at 12:11:14, Andreas Möller (notifications@github.com) wrote:

@GeeH

Got access now!

However, what is apparent from #296 (comment):



Sorry to bug you with this, but can you please have a look at the GitHub Application setting again?

**Comment by localheinz** [comment]
@GeeH 

Cool, you are :crown:!

**Comment by gianarb** [comment]
:tada: !!! :D

**Comment by ins0** [comment]
HYPE :+1:

**Comment by GeeH** [comment]
![e47a71a9](https://cloud.githubusercontent.com/assets/613376/6314742/6479591e-b9e2-11e4-980e-8fc5dc3f8c31.png)

**Comment by ins0** [comment]
if the client id is equal to ``e00c0cc9c5eab5a04653`` we should ask for github support, this is too strange

**Comment by GeeH** [comment]
I’ve confirmed the client ID and secret are correct


On 21 February 2015 at 16:11:18, Marco Rieger (notifications@github.com) wrote:

if the client id is equal to e00c0cc9c5eab5a04653 we should ask for github support, this is too strange

**Comment by localheinz** [comment]
Great news, thanks to @weierophinney we now have a new GitHub applicatio under the realm of `zendframework` and are able to sign in, at least when going to http://zfmodules.com.

Looking into redirecting from http://modules.zendframework.com to http://zfmodules.com.

**Comment by localheinz** [comment]
Forgot to add some :tada:!

**Comment by gianarb** [comment]
:tada: beautifullll stuff!

**Comment by localheinz** [comment]
@weierophinney has also set up a redirect from http://modules.zendframework.com to http://zfmodules.com

Closing! :cake:
