### ISSUE TITLE
[URGENT] All individual module pages return 500 currently

### ISSUE THREAD

**Issue by weierophinney** [zendframework/modules.zendframework.com#297]
After going to modules.zendframework.com, click on any module to get a description; as an example, http://modules.zendframework.com/neoglez/BatchManager

All of these pages result in a 500.

Ping @Hounddog @GeeH

**Comment by localheinz** [comment]
@weierophinney 

I sent you an :email:!

**Comment by GeeH** [comment]
```
2015-01-11T10:51:15-07:00 ERR (3): Exception:n1: An exception was raised while creating "HybridAuth"; no instance returnedn2: Hybridauth Library needs the CURL PHP extension.nTrace:n#0 /var/www/modules/vendor/zendframework/zendframework/library/Zend/ServiceManager/ServiceManager.php(1055): Zend\ServiceManager\ServiceManager->createServiceViaCallback(Array, 'hybridauth', 'HybridAuth')
#1 /var/www/modules/vendor/zendframework/zendframework/library/Zend/ServiceManager/ServiceManager.php(633): Zend\ServiceManager\ServiceManager->createFromFactory('hybridauth', 'HybridAuth')
#2 /var/www/modules/vendor/zendframework/zendframework/library/Zend/ServiceManager/ServiceManager.php(593): Zend\ServiceManager\ServiceManager->doCreate('HybridAuth', 'hybridauth')
#3 /var/www/modules/vendor/zendframework/zendframework/library/Zend/ServiceManager/ServiceManager.php(525): Zend\ServiceManager\ServiceManager->create(Array)
#4 /var/www/modules/module/User/src/User/Module.php(28): Zend\ServiceManager\ServiceManager->get('HybridAuth')
#5 [internal function]: User\Module->User\{closure}(Object(Zend\EventManager\Event))
#6 /var/www/modules/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(468): call_user_func(Object(Closure), Object(Zend\EventManager\Event))
#7 /var/www/modules/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(207): Zend\EventManager\EventManager->triggerListeners('api', Object(Zend\EventManager\Event), NULL)
#8 /var/www/modules/vendor/evandotpro/edp-github/src/EdpGithub/Client.php(40): Zend\EventManager\EventManager->trigger('api', Object(EdpGithub\Client))
#9 /var/www/modules/module/ZfModule/src/ZfModule/Controller/IndexController.php(36): EdpGithub\Client->api('repos')
#10 /var/www/modules/vendor/zendframework/zendframework/library/Zend/Mvc/Controller/AbstractActionController.php(83): ZfModule\Controller\IndexController->viewAction()
#11 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#12 /var/www/modules/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(468): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#13 /var/www/modules/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(207): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#14 /var/www/modules/vendor/zendframework/zendframework/library/Zend/Mvc/Controller/AbstractController.php(117): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#15 /var/www/modules/vendor/zendframework/zendframework/library/Zend/Mvc/DispatchListener.php(114): Zend\Mvc\Controller\AbstractController->dispatch(Object(ZF\ContentNegotiation\Request), Object(Zend\Http\PhpEnvironment\Response))
#16 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#17 /var/www/modules/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(468): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#18 /var/www/modules/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(207): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#19 /var/www/modules/vendor/zendframework/zendframework/library/Zend/Mvc/Application.php(313): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#20 /var/www/modules/public/index.php(21): Zend\Mvc\Application->run()
#21 {main}
```

**Comment by GeeH** [comment]
Taking comments on how to fix this, I guess there is a config file missing?

**Comment by localheinz** [comment]
@GeeH 

I'll have a look, just need to sort out a :cake: first!

**Comment by ins0** [comment]
``Hybridauth Library needs the CURL PHP extension`` ?

**Comment by Ocramius** [comment]
@GeeH requires the curl extension to be installed in production.

**Comment by localheinz** [comment]
The `Hybridauth` thing could really use some :heart:, has anyone ever had a look at it? See here https://github.com/hybridauth/hybridauth

**Comment by localheinz** [comment]
@GeeH 

Hybridauth says it needs it, right here:

* https://github.com/hybridauth/hybridauth/blob/master/composer.json#L21

**Comment by GeeH** [comment]
Closed, fixed by installing curl support.

**Comment by weierophinney** [comment]
@GeeH except that the page I linked is still showing a 500...

**Comment by GeeH** [comment]
Works on my machine! http://c.hock.in/40fcf1.png

Not there are sometimes random 500 errors because of the terrible way the app hits GitHub's API

**Comment by ins0** [comment]
Works on my system, too.

**Comment by gerardZf2Comments** [comment]
If this is all due to the Github quota limit should the advice on the Github api documentation not be followed? Their advice is to implement caching for api calls and that you can also request a higher limit which if granted would stop the site being broken for now. The api call's use a zend\http\client object which returns a http response object can be checked for  it's status code and it's headers can be checked for the 'X-RateLimit-Remaining',  and related, headers.  

It would be trivial to cache api calls on 'repos' for 24hrs (or longer if needed) so majority of api calls would then be logins. You could also discourage a general login. Most users have no need to login but could be tempted to do so to see if it changes anything. The only reason to login is to manage your git's that will appear on the site. This could be made more clear eg. change the 'login' link to a 'manage your gits' link until further functionality is made available by logging in. 

Are there any other parts to this?

**Comment by ins0** [comment]
the current github lib had a cache allready implemented and use it to call against the api endpoint, see https://github.com/EvanDotPro/EdpGithub/blob/master/src/EdpGithub/Listener/Cache.php

limited api calls can be a reason like #288 - or we need to ask github for more quota but first we need to make sure the application itself is not the real problem (and currently it is)

one problem is that this repo had only a few collaborators and most of all have other projects to maintain or simple can't spend much free time into this repo.
this shrinks the user who have access to the production server and make deployment times long.

i would love to spend even more time into this project

**Comment by gerardZf2Comments** [comment]
So if I created a branch with everything fixed would someone be available to merge it? Is this site not automatically deployed every 10 minutes as it says in the read me? Is there a branch currently being worked on to resolve this issue?

**Comment by GeeH** [comment]
Did you submit PR?


On 15 January 2015 at 10:18:29, gerardZf2Comments (notifications@github.com) wrote:

So if I created a branch with everything fixed would someone be available to merge it? Is this site not automatically deployed every 10 minutes as it says in the read me? Is there a branch currently being worked on to resolve this issue?

**Comment by gerardZf2Comments** [comment]
No. I might try but I don't want to start coding if it might conflict with another fix.

**Comment by GeeH** [comment]
We are meeting up to discuss the project, where we are, what we need to get this fixed etc at PHP Benelux next week. Until that point I’m loathed to merge anything as we may need to revert. Would you be OK to hold off on this for a week or so please?

G


On 15 January 2015 at 10:23:40, gerardZf2Comments (notifications@github.com) wrote:

No. I might try but I don't want to start coding if it might conflict with another fix.

**Comment by gerardZf2Comments** [comment]
Ok.

I read the cache class mentioned by @ins0 and have a doubt. 
There are included the lines -
if ($statusCode == 304) {
            $response =  $cache->getItem($this->cacheKey);
        } else {
            $cache->setItem($this->cacheKey, $response);

Seems like invalid responses would be cached. No?

**Comment by ins0** [comment]
yeah the current github client need some fresh PR agree - currently i think the main issue for the api limit is #288 - the issue u notice above hits only in if the quota limit is reached. however lets wait after benelux.

**Comment by GeeH** [comment]
Fixed.
