### ISSUE TITLE
Github Oauth Redirect URL missmatch

### ISSUE THREAD

**Issue by ins0** [zendframework/modules.zendframework.com#300]
the github login returns following error

``http://modules.zendframework.com/?error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdeveloper.github.com%2Fv3%2Foauth%2F%23redirect-uri-mismatch``

**Comment by snapshotpl** [comment]
Still there. I think someone need to change url in oauth configuration

**Comment by GeeH** [comment]
I need to get hold of someone with access to the Github application; on it :)

**Comment by snapshotpl** [comment]
Absolutly. Without this nobody can add something. Can you add for this `high priority` and `Bug` labels?

**Comment by diemuzi** [comment]
Same here, been trying for days and still no luck.

**Comment by basz** [comment]
I have the same issue @GeeH a recognizable problem?

**Comment by gianarb** [comment]
@basz this is a general problem.. Fix is work in progress :+1: 
You can see #296

**Comment by localheinz** [comment]
@ins0 

Closing this in favour of #296, ok?

**Comment by ins0** [comment]
:+1:
