### ISSUE TITLE
Arrange Meeting for Modules discussion

### ISSUE THREAD

**Issue by GeeH** [zendframework/modules.zendframework.com#301]
Is anyone at PHP Benelux? If so let's meet there, otherwise lets hangout - I have no idea whats going on and whats working and what isnt.

**Comment by localheinz** [comment]
I will be there and I'm looking forward to see you there!

**Comment by GeeH** [comment]
:+1:

**Comment by Ocramius** [comment]
Will be around \o/

**Comment by localheinz** [comment]
Guess this can be closed, no?

:trollface:
