### ISSUE TITLE
adding a module

### ISSUE THREAD

**Issue by gerardZf2Comments** [zendframework/modules.zendframework.com#306]
I cloned this project from git and set up a db and git keys. 
Now I try to add a module from Github and get a sql error.
"Statement could not be executed (23000 - 1048 - Column 'module_id' cannot be null)"

This is an insert statement and I believe module_id column should be auto-increment. This isn't the case if you use the .sql file in the git. 

The module mapper's insert looks like this. What's up??
 $result = parent::insert($entity, $tableName, $hydrator);
        $entity->setId($result->getGeneratedValue());
        return $result;

**Comment by adamlundrigan** [comment]
That is indeed an issue with [the schema](https://github.com/zendframework/modules.zendframework.com/blob/master/data/sql/0.sql#L11).  Could you send a PR to the sql schema which adds autoinc to that field?
