### ISSUE TITLE
Cache directory for HTMLPurifier is not writable

### ISSUE THREAD

**Issue by localheinz** [zendframework/modules.zendframework.com#315]
When navigating locally to 

* http://modules.zendframework.dev/neoglez/BatchManager

the following error is triggered

> ( ! ) Warning: Directory /Users/am/Sites/zendframework/modules.zendframework.com/vendor/ezyang/htmlpurifier/library/HTMLPurifier/DefinitionCache/Serializer not writable, please chmod to 777 in /Users/am/Sites/zendframework/modules.zendframework.com/vendor/ezyang/htmlpurifier/library/HTMLPurifier/DefinitionCache/Serializer.php on line 272

@ins0 

Do you want to take a look at this since you introduced the view helper?  I think it needs proper [configuration](http://htmlpurifier.org/live/configdoc/plain.html#Cache.SerializerPath), maybe something in `data/cache/html-purifier/` or so, otherwise it will fall back to its own default. Had this issue myself before in a different project.

**Comment by ins0** [comment]
i will

**Comment by GeeH** [comment]
Permissions error fixing now

**Comment by GeeH** [comment]
I was wrong, I missed the development.


On 23 January 2015 at 19:22:01, Marco Rieger (notifications@github.com) wrote:

i will

**Comment by ins0** [comment]
pr will show up in a few minutes

**Comment by localheinz** [comment]
Awesome, great job @ins0!
