### ISSUE TITLE
Adding modules currently unavailable

### ISSUE THREAD

**Issue by ins0** [zendframework/modules.zendframework.com#337]
because of the module hydrathor and the changes from commit https://github.com/zendframework/modules.zendframework.com/commit/c29ba795a483a42bd681cf6f61e5e08604bd8c29#diff-a97d55a60a4fa4a22114687d482b38e4R88 

adding modules result in an hard error ``DateTime to string`` failure.

**Comment by snapshotpl** [comment]
That's why I don't like ClassMethodHydrator ;)
