### ISSUE TITLE
Reduce requested GitHub permissions to minimum

### ISSUE THREAD

**Issue by adamlundrigan** [zendframework/modules.zendframework.com#342]
When signing in via GitHub the site requests a lot of permissions it shouldn't need:

![image](https://cloud.githubusercontent.com/assets/527329/5925386/c5435ca8-a63d-11e4-83e9-0eea397c30de.png)

**Comment by ins0** [comment]
:+1: will add this with hope the github login issue will be fixed in the future :trollface:
