### ISSUE TITLE
Object of class DateTime could not be converted to string

### ISSUE THREAD

**Issue by Lansoweb** [zendframework/modules.zendframework.com#412]
Ok, login with github is working now, but when i try to submit a module, i get the error on http://zfmodules.com/module/add

```
Catchable fatal error: Object of class DateTime could not be converted to string in /var/www/modules/vendor/zendframework/zendframework/library/Zend/Db/Adapter/Driver/Pdo/Statement.php on line 293
```

Thanks,
Leandro Silva

**Comment by Ocramius** [comment]
</3 hydrators :-\

**Comment by localheinz** [comment]
Talked to @ins0, waiting for deployment!

**Comment by ins0** [comment]
allready fixed and resolved when production is up to date

**Comment by Lansoweb** [comment]
Ok. Thanks guys!

**Comment by Lansoweb** [comment]
It's working now. Can close this one.

**Comment by ins0** [comment]
:+1:

**Comment by localheinz** [comment]
Thank you, guys!
