### ISSUE TITLE
Server Software Update

### ISSUE THREAD

**Issue by ins0** [zendframework/modules.zendframework.com#422]
The server is currently really outdated with the installed software and needs a dist upgrade badly.

**Comment by ins0** [comment]
ping @GeeH this blocks the complete ssl support for the page - could you please do this as this should be made from someone with server configure experience - in case something went wrong

**Comment by GeeH** [comment]
@ins0 can you be more specific please?

**Comment by ins0** [comment]
the complete server packages are outdated ... from openssl to the core, so ``apt-get  update`` and ``apt-get dist-upgrade`` should bump up all versions to a secure state.

**Comment by GeeH** [comment]
That's all I wanted to know. Your original issue wasn't particulraly helpful. I'll get this done asap.

**Comment by ins0** [comment]
sry @GeeH if i wasn't specific enough - wrote this stuff fast :smiley:

**Comment by GeeH** [comment]
Done. Please close when @localheinz has confirmed.

**Comment by localheinz** [comment]
@ins0 

Shall the two of us have a look soon?

**Comment by ins0** [comment]
@localheinz sure just ping me on twitter. in general i'm available after 5 o'clock on business days.

**Comment by localheinz** [comment]
Thank you very much, @ins0!!!
