### ISSUE TITLE
SSL Cert

### ISSUE THREAD

**Issue by ins0** [zendframework/modules.zendframework.com#424]
The ssl cert is placed by @EvanDotPro on the Server and needs to be installed for the domain on nginx - should follow after #422

**Comment by localheinz** [comment]
Thank you, @ins0!!

**Comment by snapshotpl** [comment]
@localheinz @ins0 after this login stopped working. We need to update page url in github

**Comment by ins0** [comment]
@snapshotpl this missmatch devil - yeap thanks currently working on this :+1:

**Comment by ins0** [comment]
@snapshotpl fixed
