### ISSUE TITLE
SPDY Support

### ISSUE THREAD

**Issue by ins0** [zendframework/modules.zendframework.com#425]
why not? as this is only one configuration in nginx.
should follow after #424

**Comment by GeeH** [comment]
Can you please be more informative in your tickets. Please assume that people like me have no idea what SPDY is (which I don't).

**Comment by Ocramius** [comment]
[SPDY](http://en.wikipedia.org/wiki/SPDY)

**Comment by GeeH** [comment]
I can Google thanks. However, this doesn't solve the problem of tickets being created in haste and without enough information for the contributors to asses the idea and respond accordingly. 

I can find out what SPDY is but I need to understand why, in the reporters opinion, it's a good idea to install it on the server. What benefits will it give this project, what are the downsides? Creating tickets with only one point "why not?" is not good practice in my opinion and we shouldn't encourage it.

**Comment by GeeH** [comment]
See #441 for an example of a good issue report.

**Comment by ins0** [comment]
sry @GeeH i agree that my created issue reports lacks of detailed information. will edit the other issues tonight.

i can't describe the complete spdy protocol but in general it allows the server to push resources (like images) to the client. without the spdy protocol the client is forced to request this resources from the server with result in more requests to the server. spdy is only available on ssl connections and is basically an implementation of the http2 protocol.

**Comment by localheinz** [comment]
Thank you, @ins0!!!
