### ISSUE TITLE
Redirect to zfmodules.com

### ISSUE THREAD

**Issue by snapshotpl** [zendframework/modules.zendframework.com#427]
Request http://modules.zendframework.com/feed redirects to http://zfmodules.com/, should be http://zfmodules.com/feed . We need to keep old paths to keep compatibility

**Comment by ins0** [comment]
as the redirect comes from a different zend server where we have no control this is a task for @weierophinney. can you do this please?

**Comment by localheinz** [comment]
@weierophinney 

Any idea?

**Comment by weierophinney** [comment]
Odd -- we actually keep the path when redirecting:

```
RewriteCond %{HTTP_HOST} ^modules.zendframework.com$
RewriteRule ^.* https://zfmodules.com$1 [L,R=301]
```
