### ISSUE TITLE
 A lot of configuration files, is it a best practices?

### ISSUE THREAD

**Issue by gianarb** [zendframework/modules.zendframework.com#428]
Hi!
I was thinking.. Why in this project there are a lot of [configuration files](https://github.com/zendframework/modules.zendframework.com/tree/master/config/autoload)? 

is it a best practice?
Thanks

**Comment by localheinz** [comment]
@gianarb 

I personally don't like that to much, to be honest, I'd prefer as few as possible!

**Comment by gianarb** [comment]
+1

2015-03-02 15:01 GMT+01:00 Andreas Möller <notifications@github.com>:

> @gianarb <https://github.com/gianarb>
>
> I personally don't like that to much, to be honest, I'd prefer as few as
> possible!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zendframework/modules.zendframework.com/issues/428#issuecomment-76715908>
> .
>



-- 
Gianluca Arbezzano
www.gianarb.it
