### ISSUE TITLE
List of modules from single user

### ISSUE THREAD

**Issue by gianarb** [zendframework/modules.zendframework.com#431]
Hi! I'm working at a new feature, the list of all modules for single user. Is it a good idea?
Maybe it could be a good starting point to build a public user page.

Route `/u/:owner`

We can link it into  
- "New developers" box (Now it link github)
- And into single module page if you click over the name of owner
  ![prop](https://cloud.githubusercontent.com/assets/1630267/6381539/16058a06-bd42-11e4-89a4-ac8f97d52c81.png)

**Comment by snapshotpl** [comment]
Why `/u/:owner` ? `/user/:owner` will be more clearer

**Comment by gianarb** [comment]
:+1:

**Comment by localheinz** [comment]
@gianarb 

I think this is useful!

**Comment by localheinz** [comment]
@Ocramius 

Happy to work on that, unless someone else has already started!

**Comment by Ocramius** [comment]
I assigned simply because you gave @gianarb an "ok" :-) You can ask @gianarb if he has time

**Comment by gianarb** [comment]
@localheinz This is my branch.. :) But you are free to restart
