### ISSUE TITLE
Remove puphpet?

### ISSUE THREAD

**Issue by snapshotpl** [zendframework/modules.zendframework.com#441]
What are you thing about remove puphpet files? Currently it's 12 MB of configuration files and scripts. We can still support vagrant using puphpet. How? Just keep `puphpet/confg.yaml` and `puphpet/files/*/*.sh`, other files should be ignored and can be generated manually by https://puphpet.com/ site.

**Comment by Ocramius** [comment]
The idea was to have a portable way of provisioning the VM, and tbh, the 12 MB are not a big deal.

The problem is more about puphpet being totally unmaintainable for long-term development :-\

**Comment by gianarb** [comment]
In my project I use another repository for this stuff.. I use this VM to work at zfmodules.. The problem of maintainability exists :)

**Comment by GeeH** [comment]
Any news on this, can  we either progress or close please.

**Comment by gianarb** [comment]
I don't know..
In my opinion we can delete this directory

**Comment by localheinz** [comment]
:+1:

**Comment by localheinz** [comment]
Closed with #486.
