### ISSUE TITLE
Missing Usernames in the Database

### ISSUE THREAD

**Issue by ins0** [zendframework/modules.zendframework.com#471]
I just notice that when a user is logged in and in the Db no ``username`` is present the page throws an hard error. I might be wrong but i think we got some time ago issues adding github usernames to the database.

@localheinz or someone with database access could please check if all users in the db got a value in the field ``username``?

thanks

**Comment by localheinz** [comment]
@ins0 

Noticed this some time ago as well, but checked with the database 20s ago: there are no users without user name.

**Comment by ins0** [comment]
thanks @localheinz to check this just for safety reasons :+1:
