### ISSUE TITLE
Security vulnerability detected

### ISSUE THREAD

**Issue by localheinz** [zendframework/modules.zendframework.com#507]
See

* https://www.versioneye.com/user/projects/54885d5a746eb514b0000279#tab-security

Maybe someone can take a look?

**Comment by ins0** [comment]
looks like we are not affected per se, as we use a custom login page. checking ``https://zfmodules.com/user/login`` can't be manually requested because the template can't be resolved.

this counts for both errors as far i can tell

**Comment by Ocramius** [comment]
@localheinz maybe we should add `roave/security-advisories` + `composer update`? Wanna send a PR with that change?

**Comment by localheinz** [comment]
@Ocramius 

Sounds great, but can't spare time today - maybe later tonight?

**Comment by ins0** [comment]
@localheinz @Ocramius i can send a pr in 1 hour

**Comment by Ocramius** [comment]
Thanks to both :-) I will likely merge it in the morning tho: 3:08 in LV...

**Comment by gianarb** [comment]
I don't see this page o.O

**Comment by ins0** [comment]
@gianarb me either, you need to add the project with the composer.json url :smiley:

**Comment by gianarb** [comment]
np another time :P

**Comment by Ocramius** [comment]
Here:

![security issues](http://marco-pivetta.com/screen/caps/c49749.png)

**Comment by gianarb** [comment]
:+1: Thanks
