### ISSUE TITLE
User Page

### ISSUE THREAD

**Issue by Hounddog** [zendframework/modules.zendframework.com#87]
Display information about a selected user.

Modules he owns.
Modules he contributed to

**Comment by gianarb** [comment]
This page exists..

We can close this issue..

@Ocramius are you agree?

**Comment by Ocramius** [comment]
@gianarb link to the PR?

**Comment by gianarb** [comment]
This is the user page.. 
https://zfmodules.com/user/gianarb

**Comment by Ocramius** [comment]
Yes, I'm just looking for the PR that implemented that route ;-)

**Comment by gianarb** [comment]
0d31b7d

**Comment by Ocramius** [comment]
Done via #444
